# ~/.streamlit/config.toml

[server]
# Specify the port for Streamlit to run on
port = 8501
# Allow access to Streamlit app from any IP address (useful for VPS setup)
headless = true
# Set the address to allow connections from any host
address = "0.0.0.0"



[theme]
base="dark"
font = "sans serif"

[runner]
fastReruns = false